apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-nn-pvc
  namespace: hdfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-namenode
  namespace: hdfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-namenode
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      containers:
      - name: namenode
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        env:
        - name: CLUSTER_NAME
          value: "bigdata"
        ports:
        - containerPort: 9870
        - containerPort: 9000
        volumeMounts:
        - mountPath: /hadoop/dfs/name
          name: nn-storage
      volumes:
      - name: nn-storage
        persistentVolumeClaim:
          claimName: hdfs-nn-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode-svc
  namespace: hdfs
spec:
  ports:
  - port: 9000
    name: rpc
  - port: 9870
    name: web
  selector:
    app: hdfs-namenode
