apiVersion: v1
kind: Service
metadata:
  name: spark-app
  namespace: bigdata
spec:
  type: NodePort
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30501
      protocol: TCP
      name: ui
  selector:
    app: spark-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-app
  namespace: bigdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-app
  template:
    metadata:
      labels:
        app: spark-app
    spec:
      containers:
      - name: spark-app
        image: spark-iceberg-app:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        env:
        - name: SPARK_LOCAL_IP
          value: "127.0.0.1"
        - name: HOME
          value: "/app"
        volumeMounts:
        - mountPath: /app
          name: app-code
        - mountPath: /app/warehouse
          name: warehouse
        - mountPath: /app/checkpoint_parquet
          name: checkpoint
        - mountPath: /app/data
          name: data
      volumes:
      - name: app-code
        hostPath:
          path: /home/cherricott/projects/Bigdata-main/Bigdata-main
          type: Directory
      - name: warehouse
        hostPath:
          path: /home/cherricott/projects/Bigdata-main/Bigdata-main/warehouse
          type: DirectoryOrCreate
      - name: checkpoint
        hostPath:
          path: /home/cherricott/projects/Bigdata-main/Bigdata-main/checkpoint_parquet
          type: DirectoryOrCreate
      - name: data
        hostPath:
          path: /home/cherricott/projects/Bigdata-main/Bigdata-main/data
          type: DirectoryOrCreate
